In [1]:
import numpy as np

Tính nghịch đảo ma trận

In [2]:
Y=[[2,3],[5,6]]

In [3]:
print(np.linalg.inv(Y))

[[-2.          1.        ]
 [ 1.66666667 -0.66666667]]


Tạo ma trận theo kỳ vọng và hiệp phương sai

In [12]:
means=[2,1]
cov=[[1,0],[0,1]]
X=np.random.multivariate_normal(means,cov,10)

In [13]:
X

array([[ 0.94020271,  0.22474036],
       [ 1.57684993,  2.56936089],
       [ 1.85024892,  2.07910334],
       [ 2.52695261,  0.57461344],
       [ 2.78118563,  1.19484683],
       [ 2.55209262, -0.72867857],
       [ 0.70179413,  2.00625753],
       [ 0.38875006,  1.22514416],
       [ 1.48299373,  2.03888233],
       [ 3.23961338,  0.22742983]])

In [15]:
sum(X[:,0])/10

1.804068374218056

In [16]:
sum(X[:,1])/10

1.141170014046665

Lấy ngẫu nhiên các hàng trong ma trận

In [17]:
X[np.random.choice(10,3,replace=False)] #Lấy ngẫu nhiên 3 hàng trong 10 hàng của ma trận X

array([[0.94020271, 0.22474036],
       [2.52695261, 0.57461344],
       [0.38875006, 1.22514416]])

## Lấy chỉ số hàng hoặc cột mà có giá trị nhỏ nhất

In [18]:
np.argmin(X,axis=1)

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 1], dtype=int64)

## Lấy hàng mà thỏa mãn điều kiện được cho

In [32]:
labels=np.array([1,0,1,0,1,0,1,0,0,0])
X[labels==1,:]

array([[0.94020271, 0.22474036],
       [1.85024892, 2.07910334],
       [2.78118563, 1.19484683],
       [0.70179413, 2.00625753]])